//
// Created by laura on 05/09/2021.
//

#ifndef LABORATORIODIPROGRAMMAZIONEES13_OBSERVER_H
#define LABORATORIODIPROGRAMMAZIONEES13_OBSERVER_H


class Observer {
public:
    virtual void update()=0;
};


#endif //LABORATORIODIPROGRAMMAZIONEES13_OBSERVER_H
